In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn import svm
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [6]:
a = pd.read_csv("athlete_events.csv",header=0,index_col=0)
a

,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
ID,,,,,,,,,,,,,,
1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [10]:
x = a[['Name','Sex','Age','Height','Weight','Year','Sport']]
x

,Name,Sex,Age,Height,Weight,Year,Sport
ID,,,,,,,
1,A Dijiang,M,24.0,180.0,80.0,1992,Basketball
2,A Lamusi,M,23.0,170.0,60.0,2012,Judo
3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,1920,Football
4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,1900,Tug-Of-War
5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,1988,Speed Skating
...,...,...,...,...,...,...,...
135569,Andrzej ya,M,29.0,179.0,89.0,1976,Luge
135570,Piotr ya,M,27.0,176.0,59.0,2014,Ski Jumping
135570,Piotr ya,M,27.0,176.0,59.0,2014,Ski Jumping
135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,1998,Bobsleigh
135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,2002,Bobsleigh

In [17]:
y = a[['Medal']]
y

       Medal
ID
1        NaN
2        NaN
3        NaN
4       Gold
5        NaN
...      ...
135569   NaN
135570   NaN
135570   NaN
135571   NaN
135571   NaN

[271116 rows x 1 columns]

In [18]:
XTrain,XTest,YTrain,YTest = train_test_split(x, y, test_size=0.3, random_state=55)

In [19]:
sc = StandardScaler()

In [20]:
clf = svm.SVC()

In [21]:
clf.fit(XTrain, YTrain)

ValueError: could not convert string to float: 'Evert Bastet'